### ISSUE TITLE
UUID is not working

### ISSUE THREAD

**Issue by MASTREX** [Shubham20015/Sulaah#4]
https://github.com/Shubham20015/Sulaah/blob/b4eecf42fb5f3e10a3f8f9cf00850c332fd66c7e/src/main/java/com/expense/Sulaah/entity/Transaction.java#L19

found some article which says to make UUID work with database we have to change field datatype from binary to string

**Comment by Shubham20015** [comment]
Add new controller and fix some issues #5 refer to this PR
